default: &default
  adapter: postgresql
  encoding: unicode
  pool: 20
  username: hoangnghiem
  password:
  host: localhost

development:
  <<: *default
  database: bizhub_development
test:
  <<: *default
  database: bizhub_test
production:
  <<: *default
  database: bizhub_production
