# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 21ef6672dc0e66a90bb4e7c1683b8a7c9f18c78acd83058ad9a05835edd145a71bb97d53658c1168d31e52ff734228eb321086b660fe31988a8c124aadce7248
  app_name: Bizhub
  reserved_domains: www sysadmin
  noreply_email: support@bizhub.com
  notify_exception: true
  sysadmin_emails: sysadmin@bizhub.com
  mailer_domain: bizhub.com
test:
  secret_key_base: b4786d5041d2a828b942ee9db6ff5eac745079f0d10841ee27d1c4935ca84f2d7911960dee9c80e87fea8a71ec8cda56b1f7d9401c4b131201f57c3e523e8d30

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
